<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 8 Sumarização dos dados | BIOESTATÍSTICA USANDO O R</title>
  <meta name="description" content="Capítulo 8 Sumarização dos dados | BIOESTATÍSTICA USANDO O R" />
  <meta name="generator" content="bookdown 0.27.3 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 8 Sumarização dos dados | BIOESTATÍSTICA USANDO O R" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 8 Sumarização dos dados | BIOESTATÍSTICA USANDO O R" />
  
  
  

<meta name="author" content="Petrônio Fagundes de Oliveira Filho" />


<meta name="date" content="2022-08-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="manipulando-dados-no-rstudio.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BioestatisticaR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Dados</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#o-que-são-dado"><i class="fa fa-check"></i><b>1.1</b> O que são dado?</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#população-e-amostra"><i class="fa fa-check"></i><b>1.2</b> População e Amostra</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#estimativas-e-parâmetros"><i class="fa fa-check"></i><b>1.3</b> Estimativas e Parâmetros</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#escalas-de-medição"><i class="fa fa-check"></i><b>1.4</b> Escalas de medição</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#escala-nominal"><i class="fa fa-check"></i><b>1.4.1</b> Escala Nominal</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#escala-ordinal"><i class="fa fa-check"></i><b>1.4.2</b> Escala Ordinal</a></li>
<li class="chapter" data-level="1.4.3" data-path="index.html"><a href="index.html#escala-intervalar"><i class="fa fa-check"></i><b>1.4.3</b> Escala Intervalar</a></li>
<li class="chapter" data-level="1.4.4" data-path="index.html"><a href="index.html#escala-de-razão"><i class="fa fa-check"></i><b>1.4.4</b> Escala de Razão</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#tipos-de-variáveis"><i class="fa fa-check"></i><b>1.5</b> Tipos de Variáveis</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="index.html"><a href="index.html#variáveis-numéricas"><i class="fa fa-check"></i><b>1.5.1</b> Variáveis Numéricas</a></li>
<li class="chapter" data-level="1.5.2" data-path="index.html"><a href="index.html#variáveis-categóricas"><i class="fa fa-check"></i><b>1.5.2</b> Variáveis Categóricas</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#variáveis-dependentes-e-independentes"><i class="fa fa-check"></i><b>1.6</b> Variáveis dependentes e independentes</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#leitura-adicional"><i class="fa fa-check"></i><b>1.7</b> Leitura Adicional</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html"><i class="fa fa-check"></i><b>2</b> Ambiente do R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#instalação-do-software-r-no-windows"><i class="fa fa-check"></i><b>2.1</b> Instalação do software R no Windows</a></li>
<li class="chapter" data-level="2.2" data-path="ambiente-do-r.html"><a href="ambiente-do-r.html#instalação-do-r-studio-no-windows"><i class="fa fa-check"></i><b>2.2</b> Instalação do R Studio no Windows</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="iniciando-o-rstudio.html"><a href="iniciando-o-rstudio.html"><i class="fa fa-check"></i><b>3</b> Iniciando o <em>RStudio</em></a>
<ul>
<li class="chapter" data-level="3.1" data-path="iniciando-o-rstudio.html"><a href="iniciando-o-rstudio.html#interface-do-rstudio"><i class="fa fa-check"></i><b>3.1</b> Interface do <em>RStudio</em></a></li>
<li class="chapter" data-level="3.2" data-path="iniciando-o-rstudio.html"><a href="iniciando-o-rstudio.html#iniciando-um-novo-projeto"><i class="fa fa-check"></i><b>3.2</b> Iniciando um novo projeto</a></li>
<li class="chapter" data-level="3.3" data-path="iniciando-o-rstudio.html"><a href="iniciando-o-rstudio.html#primeiro-script"><i class="fa fa-check"></i><b>3.3</b> Primeiro Script</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="matemática-básica-no-rstudio.html"><a href="matemática-básica-no-rstudio.html"><i class="fa fa-check"></i><b>4</b> Matemática Básica no <em>RStudio</em></a>
<ul>
<li class="chapter" data-level="4.1" data-path="matemática-básica-no-rstudio.html"><a href="matemática-básica-no-rstudio.html#operadores"><i class="fa fa-check"></i><b>4.1</b> Operadores</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="matemática-básica-no-rstudio.html"><a href="matemática-básica-no-rstudio.html#operadores-aritméticos"><i class="fa fa-check"></i><b>4.1.1</b> Operadores aritméticos</a></li>
<li class="chapter" data-level="4.1.2" data-path="matemática-básica-no-rstudio.html"><a href="matemática-básica-no-rstudio.html#operadores-de-atribuição"><i class="fa fa-check"></i><b>4.1.2</b> Operadores de atribuição</a></li>
<li class="chapter" data-level="4.1.3" data-path="matemática-básica-no-rstudio.html"><a href="matemática-básica-no-rstudio.html#operadores-de-comparação"><i class="fa fa-check"></i><b>4.1.3</b> Operadores de comparação</a></li>
<li class="chapter" data-level="4.1.4" data-path="matemática-básica-no-rstudio.html"><a href="matemática-básica-no-rstudio.html#operadores-lógicos"><i class="fa fa-check"></i><b>4.1.4</b> Operadores lógicos</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="matemática-básica-no-rstudio.html"><a href="matemática-básica-no-rstudio.html#logarítimo"><i class="fa fa-check"></i><b>4.2</b> Logarítimo</a></li>
<li class="chapter" data-level="4.3" data-path="matemática-básica-no-rstudio.html"><a href="matemática-básica-no-rstudio.html#raiz-quadrada"><i class="fa fa-check"></i><b>4.3</b> Raiz quadrada</a></li>
<li class="chapter" data-level="4.4" data-path="matemática-básica-no-rstudio.html"><a href="matemática-básica-no-rstudio.html#resultado-absoluto"><i class="fa fa-check"></i><b>4.4</b> Resultado absoluto</a></li>
<li class="chapter" data-level="4.5" data-path="matemática-básica-no-rstudio.html"><a href="matemática-básica-no-rstudio.html#potenciação"><i class="fa fa-check"></i><b>4.5</b> Potenciação</a></li>
<li class="chapter" data-level="4.6" data-path="matemática-básica-no-rstudio.html"><a href="matemática-básica-no-rstudio.html#exercícios"><i class="fa fa-check"></i><b>4.6</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="pacotes.html"><a href="pacotes.html"><i class="fa fa-check"></i><b>5</b> Pacotes</a>
<ul>
<li class="chapter" data-level="5.1" data-path="pacotes.html"><a href="pacotes.html#repositórios-de-pacotes"><i class="fa fa-check"></i><b>5.1</b> Repositórios de pacotes</a></li>
<li class="chapter" data-level="5.2" data-path="pacotes.html"><a href="pacotes.html#instalação-de-um-pacote"><i class="fa fa-check"></i><b>5.2</b> Instalação de um pacote</a></li>
<li class="chapter" data-level="5.3" data-path="pacotes.html"><a href="pacotes.html#carregar-um-pacote"><i class="fa fa-check"></i><b>5.3</b> Carregar um pacote</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="pacotes.html"><a href="pacotes.html#carregar-mais-de-um-pacote"><i class="fa fa-check"></i><b>5.3.1</b> Carregar mais de um pacote</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="funções.html"><a href="funções.html"><i class="fa fa-check"></i><b>6</b> Funções</a>
<ul>
<li class="chapter" data-level="6.1" data-path="funções.html"><a href="funções.html#o-que-são-funções"><i class="fa fa-check"></i><b>6.1</b> O que são funções?</a></li>
<li class="chapter" data-level="6.2" data-path="funções.html"><a href="funções.html#criando-funções"><i class="fa fa-check"></i><b>6.2</b> Criando funções</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="funções.html"><a href="funções.html#fórmula-geral"><i class="fa fa-check"></i><b>6.2.1</b> Fórmula geral</a></li>
<li class="chapter" data-level="6.2.2" data-path="funções.html"><a href="funções.html#outros-exemplos"><i class="fa fa-check"></i><b>6.2.2</b> Outros exemplos</a></li>
<li class="chapter" data-level="6.2.3" data-path="funções.html"><a href="funções.html#ativação-de-uma-função"><i class="fa fa-check"></i><b>6.2.3</b> Ativação de uma função</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="manipulando-dados-no-rstudio.html"><a href="manipulando-dados-no-rstudio.html"><i class="fa fa-check"></i><b>7</b> Manipulando Dados no RStudio</a>
<ul>
<li class="chapter" data-level="7.1" data-path="manipulando-dados-no-rstudio.html"><a href="manipulando-dados-no-rstudio.html#vetores"><i class="fa fa-check"></i><b>7.1</b> Vetores</a></li>
<li class="chapter" data-level="7.2" data-path="manipulando-dados-no-rstudio.html"><a href="manipulando-dados-no-rstudio.html#objetos"><i class="fa fa-check"></i><b>7.2</b> Objetos</a></li>
<li class="chapter" data-level="7.3" data-path="manipulando-dados-no-rstudio.html"><a href="manipulando-dados-no-rstudio.html#manipulando-dados-numéricos"><i class="fa fa-check"></i><b>7.3</b> Manipulando dados numéricos</a></li>
<li class="chapter" data-level="7.4" data-path="manipulando-dados-no-rstudio.html"><a href="manipulando-dados-no-rstudio.html#manipulando-dados-categóricos"><i class="fa fa-check"></i><b>7.4</b> Manipulando dados categóricos</a></li>
<li class="chapter" data-level="7.5" data-path="manipulando-dados-no-rstudio.html"><a href="manipulando-dados-no-rstudio.html#dataframes-ou-banco-de-dados"><i class="fa fa-check"></i><b>7.5</b> Dataframes ou Banco de dados</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="manipulando-dados-no-rstudio.html"><a href="manipulando-dados-no-rstudio.html#criando-um-banco-de-dados"><i class="fa fa-check"></i><b>7.5.1</b> Criando um banco de dados</a></li>
<li class="chapter" data-level="7.5.2" data-path="manipulando-dados-no-rstudio.html"><a href="manipulando-dados-no-rstudio.html#salvando-os-arquivos-no-seu-diretório"><i class="fa fa-check"></i><b>7.5.2</b> Salvando os arquivos no seu diretório</a></li>
<li class="chapter" data-level="7.5.3" data-path="manipulando-dados-no-rstudio.html"><a href="manipulando-dados-no-rstudio.html#importando-um-banco-de-dados"><i class="fa fa-check"></i><b>7.5.3</b> Importando um banco de dados</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html"><i class="fa fa-check"></i><b>8</b> Sumarização dos dados</a>
<ul>
<li class="chapter" data-level="8.1" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html#medidas-de-tendência-central"><i class="fa fa-check"></i><b>8.1</b> Medidas de tendência central</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html#média"><i class="fa fa-check"></i><b>8.1.1</b> Média</a></li>
<li class="chapter" data-level="8.1.2" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html#mediana"><i class="fa fa-check"></i><b>8.1.2</b> Mediana</a></li>
<li class="chapter" data-level="8.1.3" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html#moda"><i class="fa fa-check"></i><b>8.1.3</b> Moda</a></li>
<li class="chapter" data-level="8.1.4" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html#quantil"><i class="fa fa-check"></i><b>8.1.4</b> Quantil</a></li>
<li class="chapter" data-level="8.1.5" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html#média-aparada"><i class="fa fa-check"></i><b>8.1.5</b> Média aparada</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html#medidas-de-dispersão"><i class="fa fa-check"></i><b>8.2</b> Medidas de Dispersão</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html#amplitude"><i class="fa fa-check"></i><b>8.2.1</b> Amplitude</a></li>
<li class="chapter" data-level="8.2.2" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html#intervalo-interquartil"><i class="fa fa-check"></i><b>8.2.2</b> Intervalo Interquartil</a></li>
<li class="chapter" data-level="8.2.3" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html#variância-e-desvio-padrão"><i class="fa fa-check"></i><b>8.2.3</b> Variância e Desvio Padrão</a></li>
<li class="chapter" data-level="8.2.4" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html#coeficiente-de-variação"><i class="fa fa-check"></i><b>8.2.4</b> Coeficiente de Variação</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html#funções-descritivas-no-r"><i class="fa fa-check"></i><b>8.3</b> Funções descritivas no R</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html#funções-describe-e-describeby"><i class="fa fa-check"></i><b>8.3.1</b> Funções <code>describe</code> e <code>describeBy</code></a></li>
<li class="chapter" data-level="8.3.2" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html#funções-group_by-e-summarise"><i class="fa fa-check"></i><b>8.3.2</b> Funções <code>group_by</code> e <code>summarise</code></a></li>
<li class="chapter" data-level="8.3.3" data-path="sumarização-dos-dados.html"><a href="sumarização-dos-dados.html#função-summary"><i class="fa fa-check"></i><b>8.3.3</b> Função <code>summary</code></a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BIOESTATÍSTICA USANDO O R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sumarização-dos-dados" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Capítulo  8</span> Sumarização dos dados<a href="sumarização-dos-dados.html#sumarização-dos-dados" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Um conjunto de dados brutos devem ser descritos, organizando-os em forma de tabelas e de gráficos que dão uma “imagem” dos dados, permitindo que se observe o seu aspecto e como eles se comportam.<br />
As maneiras mais usadas para resumir o conjunto de dados são:</p>
<ul>
<li>Primeiro, um valor em torno do qual os dados têm uma tendência para se reunir ou se agrupar, denominado de medida sumária de localização ou medida de tendência central.</li>
<li>Em segundo lugar, um valor que mede o grau em que os dados se dispersam, denominado de medida de dispersão ou variabilidade.</li>
</ul>
<p>Para trabalhar nesta seção, vamos usar os seguintes pacotes:</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="sumarização-dos-dados.html#cb178-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(dplyr, readxl, psych)</span></code></pre></div>
<p>E o arquivo <code>dadosMater15.xlsx</code>que pode ser obtido <a href="https://github.com/petronioliveira/Arquivos/raw/master/dadosMater15.xlsx">aqui</a> e baixado para o seu diretório de trabalho.</p>
<p>Agora, vamos criar um objeto, <code>mater15</code>, para receber os dados, a partir do diretório de trabalho, executando o seguinte código:</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="sumarização-dos-dados.html#cb179-1" aria-hidden="true" tabindex="-1"></a>mater15 <span class="ot">&lt;-</span> <span class="fu">read_excel</span> (<span class="st">&quot;C:/Users/petro/Dropbox/Git_repositório/Arquivos/dadosMater15.xlsx&quot;</span>)</span></code></pre></div>
<p>O caminho (<em>path</em>), usado no comando, é o do arquivo no computador do autor. Você deverá escrever o caminho no seu computador. Observe o uso de barra comum (não invertida). Se o arquivo foi baixado no diretório de trabalho ativo, basta escrever <code>"dadosMater15.xlsx"</code>.</p>
<div id="medidas-de-tendência-central" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Medidas de tendência central<a href="sumarização-dos-dados.html#medidas-de-tendência-central" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="média" class="section level3 hasAnchor" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> Média<a href="sumarização-dos-dados.html#média" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A média ( <span class="math inline">\(\overline{x}\)</span> ) é a mais usada medida de tendência central. Ela é calculada pela razão entre a soma de todas as observações de um conjunto de dados e o total de observações.<br />
Com os dados dos pesos dos recém-nascidos (<code>pesoRN</code>) do arquivo <code>dadosMater15.xlsx</code>, podemos calcular a média aritmética, usando a função <code>mean ()</code>. A média é mais adequada para medidas numéricas simétricas.</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="sumarização-dos-dados.html#cb180-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(mater15<span class="sc">$</span>pesoRN)</span></code></pre></div>
<pre><code>## [1] 3238.067</code></pre>
<p>Se no conjunto de dados houvesse algum valor ausente (<em>missing</em>), o comando mostraria o resultado como NA (<em>not available</em>). Para corrigir isto, basta colocar o argumento <code>na.rm = TRUE</code> na função <code>mean()</code>. Assim, o <strong>R</strong> vai retornar a média, ignorando os valores ausentes.</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="sumarização-dos-dados.html#cb182-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span> (mater15<span class="sc">$</span>pesoRN, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 3238.067</code></pre>
</div>
<div id="mediana" class="section level3 hasAnchor" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Mediana<a href="sumarização-dos-dados.html#mediana" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A mediana (Md) representa o valor central em uma série ordenada de valores. Assim, metade dos valores será igual ou menor que o valor mediano e a outra metade igual ou maior do que ele.<br />
No <strong>R</strong>, usa-se a função <code>median ()</code> para calcular o valor da mediana. Vanos utilizar a variável <code>mater15$apgar1</code>. Como o Apgar é um escore, a medida resumidora mais adequada é a mediana. Em primeiro lugar verifica-se a presença NA:</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="sumarização-dos-dados.html#cb184-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (mater15<span class="sc">$</span>apgar1)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   4.000   8.000   8.000   7.667   8.500   9.000</code></pre>
<p>Não existe dados omissos nessa amostra. Portanto, o uso do argumento <code>na.rm = TRUE</code> é desnecessário.</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="sumarização-dos-dados.html#cb186-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span> (mater15<span class="sc">$</span>apgar1)</span></code></pre></div>
<pre><code>## [1] 8</code></pre>
</div>
<div id="moda" class="section level3 hasAnchor" number="8.1.3">
<h3><span class="header-section-number">8.1.3</span> Moda<a href="sumarização-dos-dados.html#moda" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Moda (Mo) é o valor que ocorre com maior frequência em um conjunto de dados. Tem o menor nível de sofisticação. É usada primariamente para dados nominais porque há simplesmente contagem dos valores. Ao contrário das outras medidas de tendência central, a moda não informa nada sobre a ordem das variáveis ou variação dentro das variáveis.<br />
O <strong>R</strong> não tem uma função embutida padrão para calcular a moda. Portanto, há necessidade de ser criada uma função de usuário para calcular a moda.</p>
<p>Foi criada uma função para calcular a moda:</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="sumarização-dos-dados.html#cb188-1" aria-hidden="true" tabindex="-1"></a>moda <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb188-2"><a href="sumarização-dos-dados.html#cb188-2" aria-hidden="true" tabindex="-1"></a>  z <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="fu">as.vector</span>(x))</span>
<span id="cb188-3"><a href="sumarização-dos-dados.html#cb188-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(z)[z <span class="sc">==</span> <span class="fu">max</span>(z)]}</span></code></pre></div>
<p>Usando esta função pode-se calcular a moda para a variável <code>mater15$apgar1</code>.</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="sumarização-dos-dados.html#cb189-1" aria-hidden="true" tabindex="-1"></a><span class="fu">moda</span> (mater15<span class="sc">$</span>apgar1) </span></code></pre></div>
<pre><code>## [1] &quot;8&quot;</code></pre>
<p>A moda para essa variável é igual a mediana.</p>
</div>
<div id="quantil" class="section level3 hasAnchor" number="8.1.4">
<h3><span class="header-section-number">8.1.4</span> Quantil<a href="sumarização-dos-dados.html#quantil" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Uma medida de localização bastante utilizada são os <a href="anchor">quantis</a> que são pontos estabelecidos em intervalos regulares que dividem a amostra em subconjuntos iguais. Se estes subconjuntos são em número de 100, são denominados de <a href="anchor">percentis</a>; se são em número de em 10, são os <a href="anchor">decis</a> e em número de 4, são os <a href="anchor">quartis</a>.
A função apropriada no <strong>R</strong> para obter o quantil é <code>quantile ()</code>. Para determinar os três quartis do peso dos recém-nascidos (<code>mater15$pexoRN</code>), usa-se:</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="sumarização-dos-dados.html#cb191-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span> (mater15<span class="sc">$</span>pesoRN, <span class="fu">c</span> (<span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>))</span></code></pre></div>
<pre><code>##    25%    50%    75% 
## 2962.5 3245.0 3515.0</code></pre>
<p>Observe que o percentil 50º é igual a mediana. O percentil 75º é o ponto do conjunto de dados onde 75% dos recém-nascidos têm um peso inferior a 3515,0g e 25% está acima deste valor.</p>
</div>
<div id="média-aparada" class="section level3 hasAnchor" number="8.1.5">
<h3><span class="header-section-number">8.1.5</span> Média aparada<a href="sumarização-dos-dados.html#média-aparada" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As médias aparadas são estimadores robustos da tendência central. Para calcular uma média aparada, é removida uma quantidade predeterminada de observações em cada lado de uma distribuição e realizada a média das observações restantes. Um exemplo de média aparada é a própria mediana.<br />
A base <strong>R</strong> tem como calcular a média aparada acrescentando o argumento <code>trim =</code>, proporção a ser aparada. Se for aparado 20%, usa-se <code>trim = 0.2</code>. isto significa que serão removidos 20% dos dados dos dois extremos. No caso da amostra de 15 recém-nascidos, serão removidos três valores mais baixos e três valores mais altos, passando a mostra a ter 9 valores, e a média aparada será a média destes 9 valores. O comando para obter a média aparada é:</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="sumarização-dos-dados.html#cb193-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span> (mater15<span class="sc">$</span>pesoRN, <span class="at">na.rm =</span> <span class="cn">TRUE</span>, <span class="at">trim =</span> <span class="fl">0.20</span>)</span></code></pre></div>
<pre><code>## [1] 3253.889</code></pre>
</div>
</div>
<div id="medidas-de-dispersão" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Medidas de Dispersão<a href="sumarização-dos-dados.html#medidas-de-dispersão" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="amplitude" class="section level3 hasAnchor" number="8.2.1">
<h3><span class="header-section-number">8.2.1</span> Amplitude<a href="sumarização-dos-dados.html#amplitude" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A amplitude de um grupo de medições é definida como a diferença entre a maior observação e a menor.<br />
No conjunto de dados dos pesos dos recém-nascidos, a amplitude pode ser obtida, no <em>R</em>, com a função <code>range ()</code>, que retorna o valor mínimo e o máximo.</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="sumarização-dos-dados.html#cb195-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span> (mater15<span class="sc">$</span>pesoRN, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 2051 4070</code></pre>
</div>
<div id="intervalo-interquartil" class="section level3 hasAnchor" number="8.2.2">
<h3><span class="header-section-number">8.2.2</span> Intervalo Interquartil<a href="sumarização-dos-dados.html#intervalo-interquartil" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A intervalo interquartil (IIQ), também conhecido como amplitude interquartil (AIQ) é uma forma de média aparada. É simplesmente a diferença entre o terceiro e o primeiro quartil, ou seja, a diferença entre o percentil 75 e o percentil 25.
Considere a escolaridade (<code>anosEst</code>) das parturientes da amostra <code>dadosMater15.xlsx</code>. Os percentis 25 e 75 são obtidos por:</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="sumarização-dos-dados.html#cb197-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span> (mater15<span class="sc">$</span>anosEst, <span class="fu">c</span>(<span class="fl">0.25</span>,<span class="fl">0.75</span>))</span></code></pre></div>
<pre><code>## 25% 75% 
##   6   8</code></pre>
<p>Também podeser usada a função <code>summary ()</code>:</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="sumarização-dos-dados.html#cb199-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mater15<span class="sc">$</span>anosEst)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       4       6       7       7       8      11</code></pre>
<p>Portanto, o IIQ está entre 6 a 8 anos de estudo ou, 8 – 6 = 2 anos de estudos completos. Em outras palavras, 50% das mulheres desta amostra têm de 6 a 8 anos de estudo.</p>
</div>
<div id="variância-e-desvio-padrão" class="section level3 hasAnchor" number="8.2.3">
<h3><span class="header-section-number">8.2.3</span> Variância e Desvio Padrão<a href="sumarização-dos-dados.html#variância-e-desvio-padrão" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A variância e o desvio padrão fornecem uma indicação de quão aglomerados em torno da média os dados de uma amostra estão. Estes tipos de medidas representam desvios da média.<br />
No <strong>R</strong> existem as funções <code>sd ()</code> e <code>var ()</code>, também incluídas no <strong>R</strong> base, que facilmente calculam essas medidas de dispersão. Usando a variável <code>mater15$pesoRN</code>, tem-se:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="sumarização-dos-dados.html#cb201-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span> (mater15<span class="sc">$</span>pesoRN)</span></code></pre></div>
<pre><code>## [1] 523.318</code></pre>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="sumarização-dos-dados.html#cb203-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(mater15<span class="sc">$</span>pesoRN)</span></code></pre></div>
<pre><code>## [1] 273861.8</code></pre>
<p>O desvio padrão é a raiz quadrada da variância:</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="sumarização-dos-dados.html#cb205-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span> (<span class="fu">var</span>(mater15<span class="sc">$</span>pesoRN))</span></code></pre></div>
<pre><code>## [1] 523.318</code></pre>
<p>A variância e desvio padrão são medidas de variabilidade. Representam quão bem a média representa os dados. Informa se ela está funcionando bem como modelo. Pequenos desvios padrão mostram que existe pouca variabilidade nos dados, que eles se aproximam da média. Quando existe um grande desvio padrão, a média não é muito precisa para representar os dados.</p>
</div>
<div id="coeficiente-de-variação" class="section level3 hasAnchor" number="8.2.4">
<h3><span class="header-section-number">8.2.4</span> Coeficiente de Variação<a href="sumarização-dos-dados.html#coeficiente-de-variação" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O desvio padrão por si só tem limitações. Um desvio padrão de duas unidades pode ser considerado pequeno para um conjunto de valores cuja média é 100. Entretanto, se a média for 5, ele se torna muito grande. Além disso, o desvio padrão por ser expresso na mesma unidade dos dados, não permite aplicá-lo na comparação de dois ou mais conjunto de dados que têm unidades diferentes.
Para eliminar essas limitações, é possível caracterizar a dispersão ou variabilidade dos dados em termos relativos, usando uma medida denominada Coeficiente de Variação (CV), também conhecido como como Desvio Padrão Relativo ou Coeficiente de Variação de Pearson. É expresso, em geral como uma porcentagem, sendo definido como a razão do desvio padrão pela média:</p>
<p><span class="math display">\[
CV = \frac{s}{\overline{x}}
\]</span></p>
<p>Multiplicando o valor da equação por 100 tem-se o CV percentual.<br />
O <strong>R</strong> não possui uma função específica para calcular o CV. Foi criada uma função específica para isso,já multiplicada por 100.</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="sumarização-dos-dados.html#cb207-1" aria-hidden="true" tabindex="-1"></a>coef_var <span class="ot">&lt;-</span> <span class="cf">function</span> (valores) {</span>
<span id="cb207-2"><a href="sumarização-dos-dados.html#cb207-2" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">sd</span>(valores, <span class="at">na.rm=</span>T) <span class="sc">/</span> <span class="fu">mean</span>(valores, <span class="at">na.rm=</span>T))<span class="sc">*</span><span class="dv">100</span>}</span></code></pre></div>
<p>Portanto, o CV da variável <code>mater15$pesoRN</code> é igual a:</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="sumarização-dos-dados.html#cb208-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef_var</span> (mater15<span class="sc">$</span>pesoRN)</span></code></pre></div>
<pre><code>## [1] 16.16144</code></pre>
<p>Se usarmos outra variável do banco de dados, por exemplo, mater15$idadeMae, o CV será igual a:</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="sumarização-dos-dados.html#cb210-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef_var</span> (mater15<span class="sc">$</span>idadeMae)</span></code></pre></div>
<pre><code>## [1] 25.83343</code></pre>
<p>O peso do recem-nascido tem um CV = 16.2 e a idade materna um CV = 25.8, mostrando que esta tem uma maior variabilidade. Quanto menor o desvio padrão, menor o CV e, consequentemente, menor a variabilidade. Um CV <span class="math inline">\(\ge\)</span> 50%, sugere que a variável tenha uma distribuição assimétrica.</p>
</div>
</div>
<div id="funções-descritivas-no-r" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Funções descritivas no R<a href="sumarização-dos-dados.html#funções-descritivas-no-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="funções-describe-e-describeby" class="section level3 hasAnchor" number="8.3.1">
<h3><span class="header-section-number">8.3.1</span> Funções <code>describe</code> e <code>describeBy</code><a href="sumarização-dos-dados.html#funções-describe-e-describeby" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Essas funções pertencem ao pacote <code>psych</code> e podem ser usada para se obter medidas descritivas, como média, desvion padrão, mediana, média aparada (padrão = 0.1),desvio absoluto mediano, , mínimo, máximo, assimetria (skew), curtose, erro padrão:</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="sumarização-dos-dados.html#cb212-1" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span> (mater15<span class="sc">$</span>pesoRN)</span></code></pre></div>
<pre><code>##    vars  n    mean     sd median trimmed    mad  min  max range skew
## X1    1 15 3238.07 523.32   3245 3265.38 563.39 2051 4070  2019 -0.4
##    kurtosis     se
## X1     -0.3 135.12</code></pre>
<p>A variável <code>sexo</code> do recém-nascido encontra-se no banco de dados como uma variável numérica:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="sumarização-dos-dados.html#cb214-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span> (mater15<span class="sc">$</span>sexo)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>E deve ser transformada para se conhecer o peso dos recém-nascidos por sexo:</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="sumarização-dos-dados.html#cb216-1" aria-hidden="true" tabindex="-1"></a>mater15<span class="sc">$</span>sexo <span class="ot">&lt;-</span> <span class="fu">factor</span> (mater15<span class="sc">$</span>sexo, </span>
<span id="cb216-2"><a href="sumarização-dos-dados.html#cb216-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">label =</span> <span class="fu">c</span> (<span class="st">&quot;masculino&quot;</span>, <span class="st">&quot;feminino&quot;</span>))</span></code></pre></div>
<p>Depois da transformação, podemos usar a função describeBy () para obter o peso para cada sexo:</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="sumarização-dos-dados.html#cb217-1" aria-hidden="true" tabindex="-1"></a><span class="fu">describeBy</span> (mater15<span class="sc">$</span>pesoRN, </span>
<span id="cb217-2"><a href="sumarização-dos-dados.html#cb217-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">group =</span> mater15<span class="sc">$</span>sexo)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: masculino
##    vars n    mean     sd median trimmed    mad  min  max range skew
## X1    1 8 3305.75 633.07 3232.5 3305.75 437.37 2051 4070  2019 -0.6
##    kurtosis     se
## X1    -0.64 223.82
## ------------------------------------------------------- 
## group: feminino
##    vars n    mean     sd median trimmed    mad  min  max range skew
## X1    1 7 3160.71 397.93   3340 3160.71 607.87 2630 3750  1120 0.02
##    kurtosis    se
## X1    -1.71 150.4</code></pre>
</div>
<div id="funções-group_by-e-summarise" class="section level3 hasAnchor" number="8.3.2">
<h3><span class="header-section-number">8.3.2</span> Funções <code>group_by</code> e <code>summarise</code><a href="sumarização-dos-dados.html#funções-group_by-e-summarise" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Essas funções estão contidas no pacote <code>dplyr</code> (clique <a href="https://www.dropbox.com/s/9geund7drwdvi2x/Manipulando-Dados-com-o-dplyr.html?dl=0">aqui</a> para explorar mais este pacote). Elas podem ser usadas juntas com o operador <a href="anchor">pipe</a>. Este é utilizado para encadear funções, ou seja, chama-se uma função e, em seguida, passar o resultado para outra função e dessa para outra, de uma forma que seja facilmente legível. Por exemplo:</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="sumarização-dos-dados.html#cb219-1" aria-hidden="true" tabindex="-1"></a>mater15 <span class="sc">%&gt;%</span> </span>
<span id="cb219-2"><a href="sumarização-dos-dados.html#cb219-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sexo) <span class="sc">%&gt;%</span> </span>
<span id="cb219-3"><a href="sumarização-dos-dados.html#cb219-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span> (<span class="at">n =</span> <span class="fu">n</span> (),</span>
<span id="cb219-4"><a href="sumarização-dos-dados.html#cb219-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">media =</span> <span class="fu">mean</span>(pesoRN),</span>
<span id="cb219-5"><a href="sumarização-dos-dados.html#cb219-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">dp =</span> <span class="fu">sd</span> (pesoRN),</span>
<span id="cb219-6"><a href="sumarização-dos-dados.html#cb219-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">mediana =</span> <span class="fu">median</span>(pesoRN),</span>
<span id="cb219-7"><a href="sumarização-dos-dados.html#cb219-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">IQQ =</span> <span class="fu">IQR</span> (pesoRN),</span>
<span id="cb219-8"><a href="sumarização-dos-dados.html#cb219-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">cv =</span> <span class="fu">coef_var</span> (pesoRN))</span></code></pre></div>
<pre><code>## # A tibble: 2 × 7
##   sexo          n media    dp mediana   IQQ    cv
##   &lt;fct&gt;     &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 masculino     8 3306.  633.   3232.  580   19.2
## 2 feminino      7 3161.  398.   3340   522.  12.6</code></pre>
<p>Os comandos chamam o banco de dado <code>mater15</code>, filtram a variável <code>sexo</code> deste banco e depois calculam varias medidas decritivas da variável <code>pesoRN.</code></p>
</div>
<div id="função-summary" class="section level3 hasAnchor" number="8.3.3">
<h3><span class="header-section-number">8.3.3</span> Função <code>summary</code><a href="sumarização-dos-dados.html#função-summary" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A função <code>summary ()</code> fornece a os quantis, o máximo, o mínimo e a média de uma variável ou do banco de dados.</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="sumarização-dos-dados.html#cb221-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mater15<span class="sc">$</span>idadeMae)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   19.00   20.50   23.00   24.87   26.50   40.00</code></pre>
<p>Para maiores esclarecimentos, consulte:</p>
<p><a href="https://statsandr.com/blog/descriptive-statistics-in-r/" class="uri">https://statsandr.com/blog/descriptive-statistics-in-r/</a><br />
<a href="http://www.sthda.com/english/wiki/descriptive-statistics-and-graphics" class="uri">http://www.sthda.com/english/wiki/descriptive-statistics-and-graphics</a>
<a href="https://learningstatisticswithr.com/book/descriptives.html" class="uri">https://learningstatisticswithr.com/book/descriptives.html</a></p>
<p></br>
</br></p>

</div>
</div>
</div>







            </section>

          </div>
        </div>
      </div>
<a href="manipulando-dados-no-rstudio.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/petronioliveira/ini-bio-r/edit/master/08-sumarizandoDados.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/petronioliveira/ini-bio-r/blob/master/08-sumarizandoDados.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
